#!/bin/bash

if [[ "${NGINX_CONFIG_FILE:-}" == "" ]]; then
    NGINX_CONFIG_FILE=/etc/dhcp/dhcpd.conf
fi

IFS='' read -r -d '' NGINX_TEMPLATE <<"EOL"
server {
    listen       ${HTTP_SERVER_PORT};
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location /monolithic {
        root   /data/;
        index  index.html index.htm;
        autoindex on;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
EOL

NGINX_CONFIG=$( eval "echo -e \"${NGINX_TEMPLATE//\"/\\\"}\"" )

mkdir -p $(dirname ${NGINX_CONFIG_FILE})
echo -e "${NGINX_CONFIG}" > ${NGINX_CONFIG_FILE}