# Default values for cnnos-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubernetes-dashboard:
  dashboard:
    service:
      type: NodePort
      externalPort: 32000
      
metrics-server:
  args:
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-insecure-tls
