{{- if .Values.create.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default ( include "eck-operator.fullname" . ) .Values.secretNameOverride }}
  namespace: {{ .Release.Namespace }}
{{- end -}}