{{- if .Values.create.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default ( include "eck-operator.fullname" . ) .Values.serviceAccountNameOverride }}
  namespace: {{ .Release.Namespace }}
{{- end -}}