apiVersion: types.kubefed.io/v1beta1
kind: FederatedClusterRole
metadata:
  name: {{ .Values.fabricName }}-kube-state-metrics
spec:
  template:
    metadata:
      name: {{ .Values.fabricName }}-kube-state-metrics
    rules:
    - apiGroups:
      - certificates.k8s.io
      resources:
      - certificatesigningrequests
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - list
      - watch
    - apiGroups:
      - batch
      resources:
      - cronjobs
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      - apps
      resources:
      - daemonsets
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      - apps
      resources:
      - deployments
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - endpoints
      verbs:
      - list
      - watch
    - apiGroups:
      - autoscaling
      resources:
      - horizontalpodautoscalers
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      resources:
      - ingresses
      verbs:
      - list
      - watch
    - apiGroups:
      - batch
      resources:
      - jobs
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - limitranges
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - persistentvolumeclaims
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - persistentvolumes
      verbs:
      - list
      - watch
    - apiGroups:
      - policy
      resources:
      - poddisruptionbudgets
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      - apps
      resources:
      - replicasets
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - replicationcontrollers
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - resourcequotas
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - list
      - watch
    - apiGroups:
      - apps
      resources:
      - statefulsets
      verbs:
      - list
      - watch
  placement:
{{- if .Values.federation.clusterSelector }}
    clusterSelector:
{{ .Values.federation.clusterSelector | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.clusters }}
    clusters:
{{ .Values.federation.clusters | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.overrides.namespaceEnabled }}
  overrides:
{{ .Values.federation.overrides.namespace | toYaml | indent 4 }}
{{- end }}