apiVersion: types.kubefed.io/v1beta1
kind: FederatedPodSecurityPolicy
metadata:
  name: {{ .Values.fabricName }}-node-exporter
  labels:
    snaproute.com/cnnos-fabric: {{ .Values.fabricName }}
    app.kubernetes.io/name: node-exporter
spec:
  template:
    metadata:
      name: {{ .Values.fabricName }}-node-exporter
      namespace: {{ .Release.Namespace }}
      labels:
        snaproute.com/cnnos-fabric: {{ .Values.fabricName }}
        app.kubernetes.io/name: node-exporter
        jobLabel: node-exporter
    spec:
      allowPrivilegeEscalation: true
      fsGroup:
        ranges:
        - max: 65535
          min: 0
        rule: MustRunAs
      hostNetwork: true
      hostPID: true
      hostPorts:
      - max: 65535
        min: 0
      runAsUser:
        rule: RunAsAny
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        ranges:
        - max: 65535
          min: 0
        rule: MustRunAs
      volumes:
      - configMap
      - emptyDir
      - projected
      - secret
      - downwardAPI
      - persistentVolumeClaim
      - hostPath
  placement:
{{- if .Values.federation.clusterSelector }}
    clusterSelector:
{{ .Values.federation.clusterSelector | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.clusters }}
    clusters:
{{ .Values.federation.clusters | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.overrides.namespaceEnabled }}
  overrides:
{{ .Values.federation.overrides.namespace | toYaml | indent 4 }}
{{- end }}