apiVersion: types.kubefed.io/v1beta1
kind: FederatedClusterRole
metadata:
  name: {{ .Values.fabricName }}-prometheus
spec:
  template:
    metadata:
      name: {{ .Values.fabricName }}-prometheus
    rules:
    - apiGroups:
      - ""
      resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - services/proxy
      - services/metrics
      - endpoints
      - endpoints/proxy
      - endpoints/metrics
      - pods
      - pods/proxy
      - pods/metrics
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - extensions
      resources:
      - ingresses
      verbs:
      - get
      - list
      - watch
    - nonResourceURLs:
      - /metrics
      verbs:
      - get
  placement:
{{- if .Values.federation.clusterSelector }}
    clusterSelector:
{{ .Values.federation.clusterSelector | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.clusters }}
    clusters:
{{ .Values.federation.clusters | toYaml | indent 6 }}
{{- end }}
{{- if .Values.federation.overrides.namespaceEnabled }}
  overrides:
{{ .Values.federation.overrides.namespace | toYaml | indent 4 }}
{{- end }}